services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ConnectionStrings__ApexVolleyContext=Server=sqlserver;User Id=sa;password=myPassword1!;Database=ApexVolleyDb;TrustServerCertificate=True
  
  sqlserver:
    build:
      context: ./Sqlserver
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ./Sqlserver/data:/var/opt/mssql/data
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "myPassword1!" -C -Q "SELECT COUNT(*) FROM sys.databases WHERE name = 'ApexVolleyDb';" | grep -q "1" || exit 1
      interval: 15s
      timeout: 5s
      retries: 15
      start_period: 40s