services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
       - ./uploads:/app/wwwroot/uploads

    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - DOTNET_USE_POLLING_FILE_WATCHER=true
     - ConnectionStrings__ApexVolleyContext=Server=sqlserver;User Id=sa;password=myPassword1!;Database=ApexVolleyDb;TrustServerCertificate=True
     - Stripe__SecretKey=sk_test_51SP4i820IKHClH6S57RLoY1kOqMorvZ2dSUOvxn0edKHHfjl0oqrw9lNsGOgSmp6VDOgabqNoVILNwpH0CwfNcE700hbkloKl5
     - Stripe__PublishableKey=pk_test_51SP4i820IKHClH6S2GGwjIYkplmQ5w9Q6Dh59q1X48idtSEgv6vAKoXKBan747uyxn9pPXGxanItEMzchJBKiz3x00pobjf5Zm
     - Stripe__WebhookSecret=whsec_e1148367a58b36498401cd47fac47421b505b190dc7176944319938202e1c0c7

  sqlserver:
    build:
      context: ./Sqlserver
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=myPassword1!
    volumes:
      - ./Sqlserver/data:/var/opt/mssql/data
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "myPassword1!" -C -Q "SELECT COUNT(*) FROM sys.databases WHERE name = 'ApexVolleyDb';" | grep -q "1" || exit 1
      interval: 15s
      timeout: 5s
      retries: 15
      start_period: 40s